# This configures the semantic-release tool, see https://github.com/semantic-release/semantic-release
# (installation: `npm install -g semantic-release @semantic-release/exec`, run: `npx semantic-release`).
# The tool creates a new release if the branch contains e.g. BREAKING CHANGE|feat|fix commits since the last release, following the Angular Commit Message Conventions.
# Commits that don't match the message convention or don't introduce user-facing changes will not trigger the creation of a new release.
branches:
- main
tagFormat: v${version}
plugins:
# Each plugin runs tasks during the release phases (e.g. analyzeCommits, publish).
# Therefore the order is important when multiple plugins are triggered in the same release phase.
# See https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- ['@semantic-release/exec', {
    # Builds and pushes the artifacts.
    # This is only executed when a release is created (decided in analyzeCommits phase / commit-analyzer) - not for every build.
    # see https://github.com/semantic-release/exec
    'prepareCmd': 'make prepare-release VERSION=${nextRelease.version}',
    'publishCmd': 'make release VERSION=${nextRelease.version}'
  }]
- ["@semantic-release/git", {
    # The git plugin creates a new commit for each release, updating the image tags within the manifests.
    # See https://github.com/semantic-release/git
    "assets": ["deploy/**/*", "setters.yaml"],
    "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  }]
- '@semantic-release/github'

