# kpt setter values that are applied to other KRM yaml files by `kpt fn render`.
# See also: https://kpt.dev/guides/variant-constructor-pattern
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /app-config
  name: app-config
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|app-config'
data:
  version: "0.2.1"
  name: mopidy
  title: Mopidy
  port: 6680
  healthcheck: /mopidy
  image: ghcr.io/mgoltzsche/mopidy
