apiVersion: skaffold/v3alpha1
kind: Config
metadata: # kpt-merge: /data
  name: data
  annotations:
    internal.kpt.dev/upstream-identifier: 'skaffold|Config|default|data'
    kubemate.mgoltzsche.github.com/platforms: linux/arm64/v8,linux/amd64
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: ghcr.io/mgoltzsche/mopidy # kpt-set: ${image}
    docker:
      dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  kustomize:
    paths:
    - ./deploy/default
