apiVersion: v1
kind: PersistentVolumeClaim
metadata: # kpt-merge: /mopidy-data
  name: mopidy-data
  annotations:
    internal.kpt.dev/upstream-identifier: '|PersistentVolumeClaim|default|mopidy-data'
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
      #storageClassName: local-path
  #storageClassName: local-path
