apiVersion: v1
kind: Service
metadata: # kpt-merge: /blueprint
  name: mopidy # kpt-set: ${name}
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|blueprint'
spec:
  type: ClusterIP
  ports:
  - port: 6680 # kpt-set: ${port}
    targetPort: 6680 # kpt-set: ${port}
    protocol: TCP
    name: http
  # TODO: expose mpd port
  - port: 6600
    targetPort: 6600
    protocol: TCP
    name: mpd
  selector:
    app.kubernetes.io/component: webapp
