apiVersion: v1
kind: Service
metadata: # kpt-merge: /snapcast-nodeport
  name: snapcast-nodeport
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|snapcast-nodeport'
spec:
  type: NodePort
  ports:
  - port: 1780
    targetPort: 1780
    nodePort: 31780
    protocol: TCP
    name: http
  - port: 1705
    targetPort: 1705
    nodePort: 31705
    protocol: TCP
    name: rpc
  - port: 1704
    targetPort: 1704
    nodePort: 31704
    protocol: TCP
    name: stream
  selector:
    app.kubernetes.io/component: webapp
